sudo: required
services:
    - docker
script:
    - docker build -t yousefs3d/test-docker .
    - docker images yousefs3d/test-docker 

before_deploy:
    - docker login -u yousefs3d -p Yousef232

deploy:
    provider: script
    script: docker push yousefs3d/test-docke
    on:
        branch: master